/* Copyright (C) 2026 SK hynix, Inc. */
/* SPDX-License-Identifier: MIT */

/*
 * dtoctl -- a CLI wrapper that runs a program with the DSA Transparent Offload
 * (DTO) library preloaded.  It converts command line options into the DTO_*
 * environment variables and prepends libdto.so to LD_PRELOAD so that users do
 * not need to export the variables or set up LD_PRELOAD manually.
 */

#ifndef _GNU_SOURCE
#define _GNU_SOURCE     /* for asprintf() */
#endif

#include <argp.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#ifndef LIBDTO_PATH
#define LIBDTO_PATH "/usr/lib64/libdto.so"
#endif

/* argp option keys for the long-only options (no short equivalents) */
enum {
	OPT_UMWAIT_DELAY = 0x100,
	OPT_OVERLAPPING_MEMMOVE,
	OPT_LOG_FILE,
	OPT_LOG_LEVEL,
	OPT_STATS_FILE,
	OPT_NO_MEMCPY,
	OPT_NO_MEMMOVE,
	OPT_NO_MEMSET,
	OPT_NO_MEMCMP,
	OPT_NO_CACHE_CONTROL,
	OPT_NO_AUTO_ADJUST,
	OPT_STDC_ONLY,
	OPT_STATS,
};

struct opts {
	int idx;
	char *exename;

	/* library / preload */
	const char *library;

	/* value options (NULL means "not specified") */
	const char *wait_method;
	const char *min_bytes;
	const char *cpu_fraction;
	const char *numa_aware;
	const char *wq_list;
	const char *umwait_delay;
	const char *overlapping_memmove; /* "0" or "1" after validation */
	const char *log_file;
	const char *log_level;
	const char *stats_file;

	/* flag options (false means "not specified") */
	bool no_memcpy;
	bool no_memmove;
	bool no_memset;
	bool no_memcmp;
	bool no_cache_control;
	bool no_auto_adjust;
	bool stdc_only;
	bool stats;
};

struct opts opts;

/* (a part of) output in --help option (generated by argp runtime) */
const char *argp_program_bug_address = "https://github.com/intel/DTO/issues";

/* Option groups are separated using entries with only a .doc field. */
static struct argp_option dtoctl_options[] = {
	{.doc = "Library:", .group = 1},
	{.name = "library",
	 .key = 'l',
	 .arg = "PATH",
	 .doc = "Path to libdto.so to prepend to LD_PRELOAD. Overrides $DTO_LIBRARY "
		"and the compiled-in default (" LIBDTO_PATH ")"},

	{.doc = "Offload tuning:", .group = 2},
	{.name = "wait-method",
	 .key = 'w',
	 .arg = "METHOD",
	 .doc = "How to wait for DSA completion: yield, busypoll, umwait, or tpause "
		"(sets DTO_WAIT_METHOD; default: busypoll)"},
	{.name = "min-bytes",
	 .key = 'b',
	 .arg = "BYTES",
	 .doc = "Minimum operation size offloaded to DSA (sets DTO_MIN_BYTES; "
		"default: 65536)"},
	{.name = "cpu-fraction",
	 .key = 'c',
	 .arg = "FRACTION",
	 .doc = "Fraction (0.0 <= f < 1.0) of each operation done on CPU in parallel "
		"to DSA (sets DTO_CPU_SIZE_FRACTION; default: 0.0)"},
	{.name = "numa-aware",
	 .key = 'n',
	 .arg = "MODE",
	 .doc = "NUMA awareness: 0 disable, 1 buffer-centric, 2 cpu-centric "
		"(sets DTO_IS_NUMA_AWARE; default: 0)"},
	{.name = "wq-list",
	 .key = 'q',
	 .arg = "LIST",
	 .doc = "Semicolon-separated list of DSA WQs to use, e.g. \"wq0.0;wq2.0\" "
		"(sets DTO_WQ_LIST; default: auto-discover all WQs)"},
	{.name = "umwait-delay",
	 .key = OPT_UMWAIT_DELAY,
	 .arg = "CYCLES",
	 .doc = "Delay in cycles for the umwait instruction (sets DTO_UMWAIT_DELAY; "
		"default: 100000)"},
	{.name = "overlapping-memmove",
	 .key = OPT_OVERLAPPING_MEMMOVE,
	 .arg = "WHERE",
	 .doc = "Where to run memmove with overlapping buffers: cpu or dsa "
		"(sets DTO_OVERLAPPING_MEMMOVE_ACTION; default: cpu)"},

	{.doc = "Disable DSA offload for specific operations (DSA is used by default):",
	 .group = 3},
	{.name = "no-memcpy",
	 .key = OPT_NO_MEMCPY,
	 .doc = "Use system memcpy instead of DSA (sets DTO_DSA_MEMCPY=0)"},
	{.name = "no-memmove",
	 .key = OPT_NO_MEMMOVE,
	 .doc = "Use system memmove instead of DSA (sets DTO_DSA_MEMMOVE=0)"},
	{.name = "no-memset",
	 .key = OPT_NO_MEMSET,
	 .doc = "Use system memset instead of DSA (sets DTO_DSA_MEMSET=0)"},
	{.name = "no-memcmp",
	 .key = OPT_NO_MEMCMP,
	 .doc = "Use system memcmp instead of DSA (sets DTO_DSA_MEMCMP=0)"},

	{.doc = "Other toggles:", .group = 4},
	{.name = "no-cache-control",
	 .key = OPT_NO_CACHE_CONTROL,
	 .doc = "Clear the DSA cache control flag to avoid cache pollution "
		"(sets DTO_DSA_CC=0; default: cache control on)"},
	{.name = "no-auto-adjust",
	 .key = OPT_NO_AUTO_ADJUST,
	 .doc = "Disable auto tuning of cpu-fraction and min-bytes "
		"(sets DTO_AUTO_ADJUST_KNOBS=0; default: auto tuning on)"},
	{.name = "stdc-only",
	 .key = OPT_STDC_ONLY,
	 .doc = "Use only the standard C memory functions, no DSA offload "
		"(sets DTO_USESTDC_CALLS=1; default: DSA offload enabled)"},

	{.doc = "Statistics and logging:", .group = 5},
	{.name = "stats",
	 .key = OPT_STATS,
	 .doc = "Enable stats collection; for debugging/profiling only "
		"(sets DTO_COLLECT_STATS=1; default: off)"},
	{.name = "stats-file",
	 .key = OPT_STATS_FILE,
	 .arg = "PATH",
	 .doc = "Write the stats histogram to PATH instead of standard output "
		"(sets DTO_STATS_FILE; default: standard output)"},
	{.name = "log-file",
	 .key = OPT_LOG_FILE,
	 .arg = "PATH",
	 .doc = "Redirect DTO output to PATH (suffixed by pid) (sets DTO_LOG_FILE; "
		"default: standard output)"},
	{.name = "log-level",
	 .key = OPT_LOG_LEVEL,
	 .arg = "LEVEL",
	 .doc = "Verbosity of DTO logging: 0, 1, or 2 (sets DTO_LOG_LEVEL; "
		"default: 0)"},

	{NULL},
};

static error_t parse_option(int key, char *arg, struct argp_state *state)
{
	struct opts *opts = state->input;

	switch (key) {
	case 'l':
		opts->library = arg;
		break;
	case 'w':
		opts->wait_method = arg;
		break;
	case 'b':
		opts->min_bytes = arg;
		break;
	case 'c':
		opts->cpu_fraction = arg;
		break;
	case 'n':
		opts->numa_aware = arg;
		break;
	case 'q':
		opts->wq_list = arg;
		break;
	case OPT_UMWAIT_DELAY:
		opts->umwait_delay = arg;
		break;
	case OPT_OVERLAPPING_MEMMOVE:
		if (!strcmp(arg, "cpu"))
			opts->overlapping_memmove = "0";
		else if (!strcmp(arg, "dsa"))
			opts->overlapping_memmove = "1";
		else {
			fprintf(stderr,
				"Error: --overlapping-memmove must be 'cpu' or 'dsa'.\n\n");
			argp_usage(state);
		}
		break;
	case OPT_NO_MEMCPY:
		opts->no_memcpy = true;
		break;
	case OPT_NO_MEMMOVE:
		opts->no_memmove = true;
		break;
	case OPT_NO_MEMSET:
		opts->no_memset = true;
		break;
	case OPT_NO_MEMCMP:
		opts->no_memcmp = true;
		break;
	case OPT_NO_CACHE_CONTROL:
		opts->no_cache_control = true;
		break;
	case OPT_NO_AUTO_ADJUST:
		opts->no_auto_adjust = true;
		break;
	case OPT_STDC_ONLY:
		opts->stdc_only = true;
		break;
	case OPT_STATS:
		opts->stats = true;
		break;
	case OPT_LOG_FILE:
		opts->log_file = arg;
		break;
	case OPT_LOG_LEVEL:
		opts->log_level = arg;
		break;
	case OPT_STATS_FILE:
		opts->stats_file = arg;
		break;

	case ARGP_KEY_ARG:
		if (state->arg_num)
			return ARGP_ERR_UNKNOWN;
		if (opts->exename == NULL) {
			/* remaining options will be processed in ARGP_KEY_ARGS */
			return ARGP_ERR_UNKNOWN;
		}
		break;

	case ARGP_KEY_ARGS:
		/* process remaining non-option arguments */
		opts->exename = state->argv[state->next];
		opts->idx = state->next;
		break;

	case ARGP_KEY_NO_ARGS:
	case ARGP_KEY_END:
		if (state->arg_num < 1)
			argp_usage(state);
		break;

	default:
		return ARGP_ERR_UNKNOWN;
	}
	return 0;
}

static void setup_child_environ(struct opts *opts)
{
	const char *lib, *cur;
	char *preload;

	/* value options: only set when explicitly specified */
	if (opts->wait_method)
		setenv("DTO_WAIT_METHOD", opts->wait_method, 1);
	if (opts->min_bytes)
		setenv("DTO_MIN_BYTES", opts->min_bytes, 1);
	if (opts->cpu_fraction)
		setenv("DTO_CPU_SIZE_FRACTION", opts->cpu_fraction, 1);
	if (opts->numa_aware)
		setenv("DTO_IS_NUMA_AWARE", opts->numa_aware, 1);
	if (opts->wq_list)
		setenv("DTO_WQ_LIST", opts->wq_list, 1);
	if (opts->umwait_delay)
		setenv("DTO_UMWAIT_DELAY", opts->umwait_delay, 1);
	if (opts->overlapping_memmove)
		setenv("DTO_OVERLAPPING_MEMMOVE_ACTION", opts->overlapping_memmove, 1);
	if (opts->log_file)
		setenv("DTO_LOG_FILE", opts->log_file, 1);
	if (opts->log_level)
		setenv("DTO_LOG_LEVEL", opts->log_level, 1);
	if (opts->stats_file)
		setenv("DTO_STATS_FILE", opts->stats_file, 1);

	/* flag options: only set when explicitly specified */
	if (opts->no_memcpy)
		setenv("DTO_DSA_MEMCPY", "0", 1);
	if (opts->no_memmove)
		setenv("DTO_DSA_MEMMOVE", "0", 1);
	if (opts->no_memset)
		setenv("DTO_DSA_MEMSET", "0", 1);
	if (opts->no_memcmp)
		setenv("DTO_DSA_MEMCMP", "0", 1);
	if (opts->no_cache_control)
		setenv("DTO_DSA_CC", "0", 1);
	if (opts->no_auto_adjust)
		setenv("DTO_AUTO_ADJUST_KNOBS", "0", 1);
	if (opts->stdc_only)
		setenv("DTO_USESTDC_CALLS", "1", 1);
	if (opts->stats)
		setenv("DTO_COLLECT_STATS", "1", 1);

	/* resolve the libdto path and prepend it to LD_PRELOAD */
	lib = opts->library ? opts->library : getenv("DTO_LIBRARY");
	if (lib == NULL)
		lib = LIBDTO_PATH;

	cur = getenv("LD_PRELOAD");
	if (cur == NULL || *cur == '\0') {
		setenv("LD_PRELOAD", lib, 1);
		return;
	}

	/*
	 * LD_PRELOAD is a colon separated list, so it can be much longer than a
	 * single path.  Allocate the result instead of formatting it into a
	 * fixed size buffer, which would silently drop part of what the caller
	 * had already preloaded.
	 */
	if (asprintf(&preload, "%s:%s", lib, cur) < 0) {
		perror("cannot build LD_PRELOAD");
		exit(EXIT_FAILURE);
	}
	setenv("LD_PRELOAD", preload, 1);
	free(preload);
}

int main(int argc, char *argv[])
{
	struct argp argp = {
		.options = dtoctl_options,
		.parser = parse_option,
		.args_doc = "<program> [<args>...]",
		.doc = "dtoctl -- run a program with DSA Transparent Offload (DTO) preloaded",
	};

	argp_parse(&argp, argc, argv, ARGP_IN_ORDER, NULL, &opts);

	/* pass only the target program and its arguments to execvp() */
	argc -= opts.idx;
	argv += opts.idx;

	setup_child_environ(&opts);

	execvp(opts.exename, argv);
	perror(opts.exename);

	return -1;
}
